// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Endpoint struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	Name                 string
	Url                  string
	Method               string
	Headers              []byte
	Body                 pgtype.Text
	IsActive             bool
	CheckIntervalMinutes int32
	NextCheckAt          pgtype.Timestamptz
	LockedAt             pgtype.Timestamptz
	ConsecutiveFailures  int32
	FailingSince         pgtype.Timestamptz
	LastCheckedAt        pgtype.Timestamptz
	LastSuccessAt        pgtype.Timestamptz
	LastStatusCode       pgtype.Int4
	LastErrorMessage     pgtype.Text
	LastTotalLatencyMs   pgtype.Int4
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type TestResult struct {
	ID                pgtype.UUID
	ExecutionID       pgtype.UUID
	EndpointID        pgtype.UUID
	StatusCode        pgtype.Int4
	IsSuccess         bool
	ErrorMessage      pgtype.Text
	DnsLookupMs       pgtype.Int4
	TcpConnectionMs   pgtype.Int4
	TlsHandshakeMs    pgtype.Int4
	TtfbMs            pgtype.Int4
	TotalLatencyMs    int32
	ResponseSizeBytes pgtype.Int4
	RedirectCount     int32
	CheckedAt         pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
